
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'a b c\n    Language : A B C\n    \n    A : a A\n      | lambda\n    \n    B : b B\n      | lambda\n    \n    C : c C\n      | c\n    \n    lambda :\n    '
    
_lr_action_items = {'a':([0,3,],[3,3,]),'b':([0,2,3,4,6,8,],[-8,6,-8,-3,6,-2,]),'c':([0,2,3,4,5,6,7,8,10,11,],[-8,-8,-8,-3,10,-8,-5,-2,10,-4,]),'$end':([1,9,10,12,],[0,-1,-7,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Language':([0,],[1,]),'A':([0,3,],[2,8,]),'lambda':([0,2,3,6,],[4,7,4,7,]),'B':([2,6,],[5,11,]),'C':([5,10,],[9,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Language","S'",1,None,None,None),
  ('Language -> A B C','Language',3,'p_Language','g1_parser.py',10),
  ('A -> a A','A',2,'p_A','g1_parser.py',26),
  ('A -> lambda','A',1,'p_A','g1_parser.py',27),
  ('B -> b B','B',2,'p_B','g1_parser.py',41),
  ('B -> lambda','B',1,'p_B','g1_parser.py',42),
  ('C -> c C','C',2,'p_C','g1_parser.py',56),
  ('C -> c','C',1,'p_C','g1_parser.py',57),
  ('lambda -> <empty>','lambda',0,'p_lambda','g1_parser.py',71),
]
